import { defineConfig, presetUno, presetIcons, presetTypography, presetWebFonts } from 'unocss'

export default defineConfig({
  presets: [
    presetUno(),
    presetIcons({
      scale: 1.2,
      extraProperties: {
        'display': 'inline-block',
        'vertical-align': 'middle',
      },
    }),
    presetTypography(),
    presetWebFonts({
      fonts: {
        sans: 'Inter:400,500,600,700',
        heading: 'Montserrat:700,800',
      },
    }),
  ],
  theme: {
    colors: {
      // Use CSS variables for theming
      primary: {
        50: 'var(--color-primary-50)',
        100: 'var(--color-primary-100)',
        200: 'var(--color-primary-200)',
        300: 'var(--color-primary-300)',
        400: 'var(--color-primary-400)',
        500: 'var(--color-primary-500)',
        600: 'var(--color-primary-600)',
        700: 'var(--color-primary-700)',
        800: 'var(--color-primary-800)',
        900: 'var(--color-primary-900)',
      },
      secondary: {
        50: 'var(--color-secondary-50)',
        100: 'var(--color-secondary-100)',
        200: 'var(--color-secondary-200)',
        300: 'var(--color-secondary-300)',
        400: 'var(--color-secondary-400)',
        500: 'var(--color-secondary-500)',
        600: 'var(--color-secondary-600)',
        700: 'var(--color-secondary-700)',
        800: 'var(--color-secondary-800)',
        900: 'var(--color-secondary-900)',
      },
      success: {
        50: 'var(--color-success-50)',
        100: 'var(--color-success-100)',
        200: 'var(--color-success-200)',
        300: 'var(--color-success-300)',
        400: 'var(--color-success-400)',
        500: 'var(--color-success-500)',
        600: 'var(--color-success-600)',
        700: 'var(--color-success-700)',
        800: 'var(--color-success-800)',
        900: 'var(--color-success-900)',
      },
      warning: {
        50: 'var(--color-warning-50)',
        100: 'var(--color-warning-100)',
        200: 'var(--color-warning-200)',
        300: 'var(--color-warning-300)',
        400: 'var(--color-warning-400)',
        500: 'var(--color-warning-500)',
        600: 'var(--color-warning-600)',
        700: 'var(--color-warning-700)',
        800: 'var(--color-warning-800)',
        900: 'var(--color-warning-900)',
      },
      danger: {
        50: 'var(--color-danger-50)',
        100: 'var(--color-danger-100)',
        200: 'var(--color-danger-200)',
        300: 'var(--color-danger-300)',
        400: 'var(--color-danger-400)',
        500: 'var(--color-danger-500)',
        600: 'var(--color-danger-600)',
        700: 'var(--color-danger-700)',
        800: 'var(--color-danger-800)',
        900: 'var(--color-danger-900)',
      },
      // Theme colors
      background: 'var(--color-background)',
      foreground: 'var(--color-foreground)',
      muted: 'var(--color-muted)',
      'muted-foreground': 'var(--color-muted-foreground)',
      card: 'var(--color-card)',
      'card-foreground': 'var(--color-card-foreground)',
      border: 'var(--color-border)',
      input: 'var(--color-input)',
      ring: 'var(--color-ring)',
    },
    fontFamily: {
      sans: 'var(--font-sans)',
      heading: 'var(--font-heading)',
    },
    borderRadius: {
      none: '0',
      sm: 'var(--radius-sm)',
      DEFAULT: 'var(--radius)',
      md: 'var(--radius-md)',
      lg: 'var(--radius-lg)',
      xl: 'var(--radius-xl)',
      '2xl': 'var(--radius-2xl)',
      full: '9999px',
    },
    spacing: {
      px: '1px',
      0: '0',
      0.5: 'var(--spacing-0-5)',
      1: 'var(--spacing-1)',
      1.5: 'var(--spacing-1-5)',
      2: 'var(--spacing-2)',
      2.5: 'var(--spacing-2-5)',
      3: 'var(--spacing-3)',
      3.5: 'var(--spacing-3-5)',
      4: 'var(--spacing-4)',
      5: 'var(--spacing-5)',
      6: 'var(--spacing-6)',
      7: 'var(--spacing-7)',
      8: 'var(--spacing-8)',
      9: 'var(--spacing-9)',
      10: 'var(--spacing-10)',
      11: 'var(--spacing-11)',
      12: 'var(--spacing-12)',
      14: 'var(--spacing-14)',
      16: 'var(--spacing-16)',
      20: 'var(--spacing-20)',
      24: 'var(--spacing-24)',
      28: 'var(--spacing-28)',
      32: 'var(--spacing-32)',
      36: 'var(--spacing-36)',
      40: 'var(--spacing-40)',
      44: 'var(--spacing-44)',
      48: 'var(--spacing-48)',
      52: 'var(--spacing-52)',
      56: 'var(--spacing-56)',
      60: 'var(--spacing-60)',
      64: 'var(--spacing-64)',
      72: 'var(--spacing-72)',
      80: 'var(--spacing-80)',
      96: 'var(--spacing-96)',
    },
  },
  shortcuts: {
    // Button shortcuts
    'btn': 'py-2 px-4 font-semibold rounded-lg shadow-md focus:outline-none focus:ring-2 focus:ring-opacity-75 transition-colors',
    'btn-primary': 'btn bg-primary-600 text-white hover:bg-primary-700 focus:ring-primary-400 dark:bg-primary-700 dark:hover:bg-primary-600',
    'btn-secondary': 'btn bg-secondary-600 text-white hover:bg-secondary-700 focus:ring-secondary-400 dark:bg-secondary-700 dark:hover:bg-secondary-600',
    'btn-success': 'btn bg-success-600 text-white hover:bg-success-700 focus:ring-success-400 dark:bg-success-700 dark:hover:bg-success-600',
    'btn-warning': 'btn bg-warning-600 text-white hover:bg-warning-700 focus:ring-warning-400 dark:bg-warning-700 dark:hover:bg-warning-600',
    'btn-danger': 'btn bg-danger-600 text-white hover:bg-danger-700 focus:ring-danger-400 dark:bg-danger-700 dark:hover:bg-danger-600',
    'btn-outline': 'btn bg-transparent border border-solid focus:ring-gray-400',
    'btn-outline-primary': 'btn-outline border-primary-600 text-primary-600 hover:bg-primary-50 dark:border-primary-400 dark:text-primary-400 dark:hover:bg-primary-900',
    
    // Alert shortcuts
    'alert': 'p-4 mb-4 rounded-lg border-l-4',
    'alert-info': 'alert bg-blue-50 border-blue-500 text-blue-800 dark:bg-blue-900/30 dark:border-blue-400 dark:text-blue-300',
    'alert-success': 'alert bg-green-50 border-green-500 text-green-800 dark:bg-green-900/30 dark:border-green-400 dark:text-green-300',
    'alert-warning': 'alert bg-yellow-50 border-yellow-500 text-yellow-800 dark:bg-yellow-900/30 dark:border-yellow-400 dark:text-yellow-300',
    'alert-danger': 'alert bg-red-50 border-red-500 text-red-800 dark:bg-red-900/30 dark:border-red-400 dark:text-red-300',
    
    // Layout shortcuts
    'container-content': 'max-w-7xl mx-auto px-4 sm:px-6 lg:px-8',
    'card': 'bg-card rounded-lg shadow-md p-6 border border-border text-card-foreground',
    'section': 'py-12',
  },
})