import { defineConfig, presetUno, presetAttributify, presetTypography, presetWebFonts, presetIcons } from 'unocss'

export default defineConfig({
  presets: [
    presetUno(),
    presetAttributify(),
    presetTypography(),
    presetIcons(),
    presetWebFonts({
      provider: 'google',
      fonts: {
        sans: [
          'Inter:100,200,300,400,500,600,700,800,900',
          'Roboto:100,300,400,500,700,900',
          'Open Sans:300,400,500,600,700,800',
          'Montserrat:100,200,300,400,500,600,700,800,900',
          'Lato:100,300,400,700,900',
          'Poppins:100,200,300,400,500,600,700,800,900',
          'Raleway:100,200,300,400,500,600,700,800,900',
          'Nunito:200,300,400,500,600,700,800,900',
          'Nunito Sans:200,300,400,600,700,800,900',
          'Merriweather:300,400,700,900',
          'Rubik:300,400,500,600,700,800,900',
          'Work Sans:100,200,300,400,500,600,700,800,900',
          'Mulish:200,300,400,500,600,700,800,900',
          'Source Sans Pro:200,300,400,600,700,900'
        ],
        mono: [
          'Fira Code:300,400,500,600,700',
          'Fira Mono:400,500,700',
          'JetBrains Mono:100,200,300,400,500,600,700,800',
          'Source Code Pro:200,300,400,500,600,700,900',
          'Ubuntu Mono:400,700',
          'Roboto Mono:100,200,300,400,500,600,700',
          'IBM Plex Mono:100,200,300,400,500,600,700'
        ],
        serif: [
          'Merriweather:300,400,700,900',
          'Playfair Display:400,500,600,700,800,900',
          'Lora:400,500,600,700',
          'Crimson Pro:200,300,400,500,600,700,800,900',
          'Libre Baskerville:400,700'
        ],
        display: [
          'Montserrat:100,200,300,400,500,600,700,800,900',
          'Oswald:200,300,400,500,600,700',
          'Bebas Neue:400',
          'Anton:400'
        ]
      },
    }),
  ],
  theme: {
    colors: {
      primary: {
        DEFAULT: 'var(--color-primary)',
        lightest: 'var(--color-primary-lightest)',
        lighter: 'var(--color-primary-lighter)',
        light: 'var(--color-primary-light)',
        medium: 'var(--color-primary-medium)',
        default: 'var(--color-primary-default)',
        dark: 'var(--color-primary-dark)',
        darker: 'var(--color-primary-darker)',
        darkest: 'var(--color-primary-darkest)',
      },
      secondary: {
        DEFAULT: 'var(--color-secondary)',
        lightest: 'var(--color-secondary-lightest)',
        lighter: 'var(--color-secondary-lighter)',
        light: 'var(--color-secondary-light)',
        medium: 'var(--color-secondary-medium)',
        default: 'var(--color-secondary-default)',
        dark: 'var(--color-secondary-dark)',
        darker: 'var(--color-secondary-darker)',
        darkest: 'var(--color-secondary-darkest)',
      },
      text: {
        primary: 'var(--color-text-primary)',
        secondary: 'var(--color-text-secondary)',
        muted: 'var(--color-text-muted)',
        inverted: 'var(--color-text-inverted)',
      },
      bg: {
        primary: 'var(--color-bg-primary)',
        secondary: 'var(--color-bg-secondary)',
        muted: 'var(--color-bg-muted)',
        overlay: 'var(--color-bg-overlay)',
      },
      border: 'var(--color-border)',
      'border-hover': 'var(--color-border-hover)',
    },
    fontFamily: {
      sans: 'var(--font-family)',
      mono: 'var(--font-family-mono)',
    },
    fontSize: {
      'xs': 'var(--font-size-xs)',
      'sm': 'var(--font-size-sm)',
      'base': 'var(--font-size-base)',
      'lg': 'var(--font-size-lg)',
      'xl': 'var(--font-size-xl)',
      '2xl': 'var(--font-size-2xl)',
      '3xl': 'var(--font-size-3xl)',
      '4xl': 'var(--font-size-4xl)',
    },
    fontWeight: {
      thin: 'var(--font-weight-thin)',
      extralight: 'var(--font-weight-extralight)',
      light: 'var(--font-weight-light)',
      normal: 'var(--font-weight-normal)',
      medium: 'var(--font-weight-medium)',
      semibold: 'var(--font-weight-semibold)',
      bold: 'var(--font-weight-bold)',
      extrabold: 'var(--font-weight-extrabold)',
      black: 'var(--font-weight-black)',
    },
    lineHeight: {
      none: 'var(--line-height-none)',
      tight: 'var(--line-height-tight)',
      snug: 'var(--line-height-snug)',
      normal: 'var(--line-height-normal)',
      relaxed: 'var(--line-height-relaxed)',
      loose: 'var(--line-height-loose)',
    },
    letterSpacing: {
      tighter: 'var(--letter-spacing-tighter)',
      tight: 'var(--letter-spacing-tight)',
      normal: 'var(--letter-spacing-normal)',
      wide: 'var(--letter-spacing-wide)',
      wider: 'var(--letter-spacing-wider)',
      widest: 'var(--letter-spacing-widest)',
    },
    spacing: {
      '0': 'var(--spacing-0)',
      'px': 'var(--spacing-px)',
      '0.5': 'var(--spacing-0-5)',
      '1': 'var(--spacing-1)',
      '1.5': 'var(--spacing-1-5)',
      '2': 'var(--spacing-2)',
      '2.5': 'var(--spacing-2-5)',
      '3': 'var(--spacing-3)',
      '3.5': 'var(--spacing-3-5)',
      '4': 'var(--spacing-4)',
      '5': 'var(--spacing-5)',
      '6': 'var(--spacing-6)',
      '7': 'var(--spacing-7)',
      '8': 'var(--spacing-8)',
      '9': 'var(--spacing-9)',
      '10': 'var(--spacing-10)',
      '11': 'var(--spacing-11)',
      '12': 'var(--spacing-12)',
      '14': 'var(--spacing-14)',
      '16': 'var(--spacing-16)',
      '20': 'var(--spacing-20)',
      '24': 'var(--spacing-24)',
      '28': 'var(--spacing-28)',
      '32': 'var(--spacing-32)',
      '36': 'var(--spacing-36)',
      '40': 'var(--spacing-40)',
      '44': 'var(--spacing-44)',
      '48': 'var(--spacing-48)',
      '52': 'var(--spacing-52)',
      '56': 'var(--spacing-56)',
      '60': 'var(--spacing-60)',
      '64': 'var(--spacing-64)',
      '72': 'var(--spacing-72)',
      '80': 'var(--spacing-80)',
      '96': 'var(--spacing-96)',
    },
    borderRadius: {
      'none': 'var(--radius-none)',
      'sm': 'var(--radius-sm)',
      'md': 'var(--radius-md)',
      'lg': 'var(--radius-lg)',
      'xl': 'var(--radius-xl)',
      '2xl': 'var(--radius-2xl)',
      '3xl': 'var(--radius-3xl)',
      'full': 'var(--radius-full)',
    },
    boxShadow: {
      'none': 'var(--shadow-none)',
      'sm': 'var(--shadow-sm)',
      'md': 'var(--shadow-md)',
      'lg': 'var(--shadow-lg)',
      'xl': 'var(--shadow-xl)',
      '2xl': 'var(--shadow-2xl)',
      'inner': 'var(--shadow-inner)',
    },
    transitionProperty: {
      'none': 'var(--transition-none)',
      'all': 'var(--transition-all)',
      'colors': 'var(--transition-colors)',
      'opacity': 'var(--transition-opacity)',
      'shadow': 'var(--transition-shadow)',
      'transform': 'var(--transition-transform)',
    },
    transitionDuration: {
      '75': 'var(--duration-75)',
      '100': 'var(--duration-100)',
      '150': 'var(--duration-150)',
      '200': 'var(--duration-200)',
      '300': 'var(--duration-300)',
      '500': 'var(--duration-500)',
      '700': 'var(--duration-700)',
      '1000': 'var(--duration-1000)',
    },
    transitionTimingFunction: {
      'linear': 'var(--ease-linear)',
      'in': 'var(--ease-in)',
      'out': 'var(--ease-out)',
      'in-out': 'var(--ease-in-out)',
    },
    zIndex: {
      '0': 'var(--z-0)',
      '10': 'var(--z-10)',
      '20': 'var(--z-20)',
      '30': 'var(--z-30)',
      '40': 'var(--z-40)',
      '50': 'var(--z-50)',
      'auto': 'var(--z-auto)',
    },
  },
  shortcuts: {
    'btn': 'inline-flex items-center justify-center rounded-md text-sm font-medium transition-colors focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-primary focus-visible:ring-offset-2 disabled:opacity-50 disabled:pointer-events-none',
    'btn-primary': 'bg-primary text-text-inverted hover:bg-primary-darker',
    'btn-secondary': 'bg-bg-muted text-text-primary hover:bg-bg-muted/80',
    'btn-outline': 'border border-border bg-transparent hover:bg-bg-muted',
    'btn-ghost': 'bg-transparent hover:bg-bg-muted',
    'btn-link': 'bg-transparent text-primary underline-offset-4 hover:underline',
  },
})